name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    uses: evolution-gaming/scala-github-actions/.github/workflows/ci.yml@22cf717df1fcf8c74ab30834cf90ab9064e93e98 # v6.?.?
